apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-test
spec:
  type: ClusterIP
  selector:
    app: nginx-test
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: api-ingress
spec:
 rules:
 - host: f1.salarsalimi.ir
   http:
     paths:
     - path: /bar
       pathType: Prefix
       backend:
         service:
           name: nginx-svc
           port:
             number: 80
 tls:
 - secretName: ss-cert
   hosts:
   - f1.salarsalimi.ir
