apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-sarole
rules:
   - apiGroups: [""]
     resources: ["pods","pods/exec"]
     verbs: ["get", "watch", "list", "cp", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-sarolebind
subjects:
  - kind: ServiceAccount
    name: backup-sa
    apiGroup:
roleRef:
  kind: Role
  name: backup-sarole
  apiGroup: rbac.authorization.k8s.io
